# Generated by Django 2.2.1 on 2019-05-31 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
        ('sightseeing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sightseeing',
            name='currency',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='money.Currency'),
        ),
        migrations.AlterField(
            model_name='sightseeing',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
